### ISSUE TITLE
Inventory for FCEV in version 1.9.2.dev0

### ISSUE THREAD

**Issue by A-Sterni** [Laboratory-for-Energy-Systems-Analysis/carculator_utils#11]
The battery is missing for FCEV if the data is exported to an excel-file.
See pull request: https://github.com/romainsacchi/carculator_utils/pull/12

Furthermore, the values for fuel cell stack and fuel cell BOP are different but both datasets refer to 1 kWe.
![FCEV](https://github.com/user-attachments/assets/d6533bd2-b62b-42b8-a1bc-92b7f659981a)

**Comment by romainsacchi** [comment]
Thanks, I merged #12 
For the values regarding stack vs. BoP: the dataset for the stack is 1 unit/kWe, while the BoP is now calculated as 6.6 kWe/kg BoP.
